config/routes.rb
Rails.application.routes.draw do
  resources :appointments

  resources :employees

  resources :physicians

  resources :patients

  resources :diagnostics

  resources :insurances

  resources :states


  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  before_save { |appointment| appointment.datetime = appointment.datetime.utc }

  belongs_to :diagnostic
  belongs_to :physician
  belongs_to :patient


  validates_uniqueness_of :datetime, scope: [:physician_id]
  validates_uniqueness_of :datetime, scope: [:patient_id]
end

app/models/diagnostic.rb
class Diagnostic < ActiveRecord::Base


end

app/models/employee.rb
class Employee < ActiveRecord::Base
  validate :bar_exists
  has_one :user , :class_name => "User"
  belongs_to :state


  def bar_exists
    if Employee.where(user_id: self.user_id).exists? then

      errors.add(:user_id, alert:"email is already assigned to a Employee")
    end

  end
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
  has_many :patient

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  validate :bar_exists, :on => [ :create]
  has_one :user , :class_name => "User"
  has_many :physician, :through =>  :appointments
  has_many :appointment
  belongs_to :state
  belongs_to :insurance


  def bar_exists
    if Patient.where(user_id: self.user_id).exists? then

      errors.add(:user_id, alert: "email is already assigned to a patient")
    end

  end

end

app/models/physician.rb
class Physician < ActiveRecord::Base
  validate :bar_exists, :on => [ :create]
  has_one :user , :class_name => "User"
  has_many :appointment
  has_many :patient, :through =>  :appointments
  belongs_to :state

  def bar_exists
    if Physician.where(user_id: self.user_id).exists? then

      errors.add(:user_id, alert: "email is already assigned to a Physician")
    end
  end
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :employee
  has_many :patient
  has_many :physician
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:patient, :physician, :admin, :employee]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :patient
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/diagnostics_controller.rb
class DiagnosticsController < ApplicationController
  before_action :set_diagnostic, only: [:show, :edit, :update, :destroy]
  before_filter :admin_only
  respond_to :html

  def index
    @diagnostics = Diagnostic.all.page params[:page]
    respond_with(@diagnostics)
  end

  def show
    respond_with(@diagnostic)
  end

  def new
    @diagnostic = Diagnostic.new
    respond_with(@diagnostic)
  end

  def edit
  end

  def create
    @diagnostic = Diagnostic.new(diagnostic_params)
    @diagnostic.save
    respond_with(@diagnostic)
  end

  def update
    @diagnostic.update(diagnostic_params)
    respond_with(@diagnostic)
  end

  def destroy
    @diagnostic.destroy
    respond_with(@diagnostic)
  end

  private
    def set_diagnostic
      @diagnostic = Diagnostic.find(params[:id])
    end

    def diagnostic_params
      params.require(:diagnostic).permit(:code, :description, :fee)
    end
  def admin_only
    unless current_user.admin?
      redirect_to(:root,alert: "Access denied")
    end
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_filter :emp_only
  respond_to :html

  def index
    @employees = Employee.all.page params[:page]
    respond_with(@employees)
  end

  def show
    respond_with(@employee)
  end

  def new
    @employee = Employee.new
    respond_with(@employee)
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)
    @employee.save
    respond_with(@employee)
  end

  def update
    @employee.update(employee_params)
    respond_with(@employee)
  end

  def destroy
    @employee.destroy
    respond_with(@employee)
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:address, :city, :state_id, :zipcode, :phone, :user_id, :ssn, :name)
    end

  def emp_only
    unless current_user.employee? || current_user.admin?
      redirect_to(:root,alert: "Access denied")
    end
  end
end

app/controllers/insurances_controller.rb
class InsurancesController < ApplicationController
  before_action :set_insurance, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @insurances = Insurance.all.page params[:page]
    respond_with(@insurances)
  end

  def show
    respond_with(@insurance)
  end

  def new
    @insurance = Insurance.new
    respond_with(@insurance)
  end

  def edit
  end

  def create
    @insurance = Insurance.new(insurance_params)
    @insurance.save
    respond_with(@insurance)
  end

  def update
    @insurance.update(insurance_params)
    respond_with(@insurance)
  end

  def destroy
    @insurance.destroy
    respond_with(@insurance)
  end

  private
    def set_insurance
      @insurance = Insurance.find(params[:id])
    end

    def insurance_params
      params.require(:insurance).permit(:name, :coverage)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  before_filter :patient_only
  respond_to :html

  def index
    @patients = Patient.all.page params[:page]
    respond_with(@patients)
  end

  def show
    respond_with(@patient)
  end

  def new
    @patient = Patient.new
    respond_with(@patient)
  end

  def edit
  end

  def create
    @patient = Patient.new(patient_params)
    @patient.save
    respond_with(@patient)
  end

  def update
    @patient.update(patient_params)
    respond_with(@patient)
  end

  def destroy
    @patient.destroy
    respond_with(@patient)
  end

  private
    def set_patient
      @patient = Patient.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(:adress, :city, :state_id, :zipcode, :phone, :insurance_id, :user_id, :name)
    end


  def patient_only
    unless current_user.patient? || current_user.admin?
      redirect_to(:root,alert: "Access denied")
    end
  end

end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @states = State.all
    respond_with(@states)
  end

  def show
    respond_with(@state)
  end

  def new
    @state = State.new
    respond_with(@state)
  end

  def edit
  end

  def create
    @state = State.new(state_params)
    flash[:notice] = 'State was successfully created.' if @state.save
    respond_with(@state)
  end

  def update
    flash[:notice] = 'State was successfully updated.' if @state.update(state_params)
    respond_with(@state)
  end

  def destroy
    @state.destroy
    respond_with(@state)
  end

  private
    def set_state
      @state = State.find(params[:id])
    end

    def state_params
      params.require(:state).permit(:state)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/diagnostics/_form.html.erb
<%= simple_form_for(@diagnostic) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :code %>
    <%= f.input :description %>
    <%= f.input :fee %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/diagnostics/edit.html.erb
<h1>Editing diagnostic</h1>

<%= render 'form' %>

<%= link_to 'Show', @diagnostic %> |
<%= link_to 'Back', diagnostics_path %>

app/views/diagnostics/index.html.erb
<h1>Listing diagnostics</h1>


<% if current_user.admin? || current_user.employee?%>
    <div class="row">
      <div class="panel panel-primary filterable">
        <div class="panel-heading">
          <h3 class="panel-title">Users</h3>
          <div class="pull-right">
            <button class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-filter"></span> Filter</button>
          </div>
        </div>
        <table class="table">
          <thead>
          <tr class="filters">
            <th><input type="text-center" class="form-control" placeholder="Code" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="Description" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="Fee" disabled></th>
            <th colspan="3"></th>

          </tr>
          </thead>
          <% @diagnostics.each do |diagnostic| %>
              <tbody>
              <tr>
                <td><%= diagnostic.code %></td>
                <td><%= diagnostic.description %></td>
                <td><%= diagnostic.fee %></td>
                <td><%= link_to 'Show', diagnostic %></td>
                <td><%= link_to 'Edit', edit_diagnostic_path(diagnostic) %></td>
                <td><%= link_to 'Destroy', diagnostic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
              </tbody>
          <% end %>
        </table>
      </div>
    </div>
<% end %>

<script type="text/javascript">
    $(document).ready(function(){
        $('.filterable .btn-filter').click(function(){
            var $panel = $(this).parents('.filterable'),
                    $filters = $panel.find('.filters input'),
                    $tbody = $panel.find('.table tbody');
            if ($filters.prop('disabled') == true) {
                $filters.prop('disabled', false);
                $filters.first().focus();
            } else {
                $filters.val('').prop('disabled', true);
                $tbody.find('.no-result').remove();
                $tbody.find('tr').show();
            }
        });

        $('.filterable .filters input').keyup(function(e){
            /* Ignore tab key */
            var code = e.keyCode || e.which;
            if (code == '9') return;
            /* Useful DOM data and selectors */
            var $input = $(this),
                    inputContent = $input.val().toLowerCase(),
                    $panel = $input.parents('.filterable'),
                    column = $panel.find('.filters th').index($input.parents('th')),
                    $table = $panel.find('.table'),
                    $rows = $table.find('tbody tr');
            /* Dirtiest filter function ever ;) */
            var $filteredRows = $rows.filter(function(){
                var value = $(this).find('td').eq(column).text().toLowerCase();
                return value.indexOf(inputContent) === -1;
            });
            /* Clean previous no-result if exist */
            $table.find('tbody .no-result').remove();
            /* Show all rows, hide filtered ones (never do that outside of a demo ! xD) */
            $rows.show();
            $filteredRows.hide();
            /* Prepend no-result row if all rows are filtered */
            if ($filteredRows.length === $rows.length) {
                $table.find('tbody').prepend($('<tr class="no-result text-center"><td colspan="'+ $table.find('.filters th').length +'">No result found</td></tr>'));
            }
        });
    });


</script>
<% if current_user.admin? || current_user.employee? %>

    <%= link_to 'New Diagnostic', new_diagnostic_path ,class:"btn btn-primary" ,role:"button" %>
<% end %>
<%= paginate @diagnostics %>

app/views/diagnostics/new.html.erb
<h1>New diagnostic</h1>

<%= render 'form' %>

<%= link_to 'Back', diagnostics_path %>

app/views/diagnostics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @diagnostic.code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @diagnostic.description %>
</p>

<p>
  <strong>Fee:</strong>
  <%= @diagnostic.fee %>
</p>

<%= link_to 'Edit', edit_diagnostic_path(@diagnostic) %> |
<%= link_to 'Back', diagnostics_path %>