config/routes.rb
Rails.application.routes.draw do
  resources :appointments

  resources :employees

  resources :physicians

  resources :patients

  resources :diagnostics

  resources :insurances

  resources :states


  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  before_save { |appointment| appointment.datetime = appointment.datetime.utc }

  belongs_to :diagnostic
  belongs_to :physician
  belongs_to :patient


  validates_uniqueness_of :datetime, scope: [:physician_id]
  validates_uniqueness_of :datetime, scope: [:patient_id]
end

app/models/diagnostic.rb
class Diagnostic < ActiveRecord::Base


end

app/models/employee.rb
class Employee < ActiveRecord::Base
  validate :bar_exists
  has_one :user , :class_name => "User"
  belongs_to :state


  def bar_exists
    if Employee.where(user_id: self.user_id).exists? then

      errors.add(:user_id, alert:"email is already assigned to a Employee")
    end

  end
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
  has_many :patient

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  validate :bar_exists, :on => [ :create]
  has_one :user , :class_name => "User"
  has_many :physician, :through =>  :appointments
  has_many :appointment
  belongs_to :state
  belongs_to :insurance


  def bar_exists
    if Patient.where(user_id: self.user_id).exists? then

      errors.add(:user_id, alert: "email is already assigned to a patient")
    end

  end

end

app/models/physician.rb
class Physician < ActiveRecord::Base
  validate :bar_exists, :on => [ :create]
  has_one :user , :class_name => "User"
  has_many :appointment
  has_many :patient, :through =>  :appointments
  belongs_to :state

  def bar_exists
    if Physician.where(user_id: self.user_id).exists? then

      errors.add(:user_id, alert: "email is already assigned to a Physician")
    end
  end
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :employee
  has_many :patient
  has_many :physician
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:patient, :physician, :admin, :employee]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :patient
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_filter :emp_only
  respond_to :html

  def index
    @employees = Employee.all.page params[:page]
    respond_with(@employees)
  end

  def show
    respond_with(@employee)
  end

  def new
    @employee = Employee.new
    respond_with(@employee)
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)
    @employee.save
    respond_with(@employee)
  end

  def update
    @employee.update(employee_params)
    respond_with(@employee)
  end

  def destroy
    @employee.destroy
    respond_with(@employee)
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:address, :city, :state_id, :zipcode, :phone, :user_id, :ssn, :name)
    end

  def emp_only
    unless current_user.employee? || current_user.admin?
      redirect_to(:root,alert: "Access denied")
    end
  end
end

app/controllers/insurances_controller.rb
class InsurancesController < ApplicationController
  before_action :set_insurance, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @insurances = Insurance.all.page params[:page]
    respond_with(@insurances)
  end

  def show
    respond_with(@insurance)
  end

  def new
    @insurance = Insurance.new
    respond_with(@insurance)
  end

  def edit
  end

  def create
    @insurance = Insurance.new(insurance_params)
    @insurance.save
    respond_with(@insurance)
  end

  def update
    @insurance.update(insurance_params)
    respond_with(@insurance)
  end

  def destroy
    @insurance.destroy
    respond_with(@insurance)
  end

  private
    def set_insurance
      @insurance = Insurance.find(params[:id])
    end

    def insurance_params
      params.require(:insurance).permit(:name, :coverage)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  before_filter :patient_only
  respond_to :html

  def index
    @patients = Patient.all.page params[:page]
    respond_with(@patients)
  end

  def show
    respond_with(@patient)
  end

  def new
    @patient = Patient.new
    respond_with(@patient)
  end

  def edit
  end

  def create
    @patient = Patient.new(patient_params)
    @patient.save
    respond_with(@patient)
  end

  def update
    @patient.update(patient_params)
    respond_with(@patient)
  end

  def destroy
    @patient.destroy
    respond_with(@patient)
  end

  private
    def set_patient
      @patient = Patient.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(:adress, :city, :state_id, :zipcode, :phone, :insurance_id, :user_id, :name)
    end


  def patient_only
    unless current_user.patient? || current_user.admin?
      redirect_to(:root,alert: "Access denied")
    end
  end

end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :set_physician, only: [:show, :edit, :update, :destroy]
  before_filter :physician_only
  respond_to :html

  def index
    @physicians = Physician.all.page params[:page]
    respond_with(@physicians)
  end

  def show
    respond_with(@physician)
  end

  def new
    @physician = Physician.new
    respond_with(@physician)
  end

  def edit
  end

  def create
    @physician = Physician.new(physician_params)
    @physician.save
    respond_with(@physician)
  end

  def update
    @physician.update(physician_params)
    respond_with(@physician)
  end

  def destroy
    @physician.destroy
    respond_with(@physician)
  end

  private
    def set_physician
      @physician = Physician.find(params[:id])
    end

    def physician_params
      params.require(:physician).permit(:address, :city, :state_id, :zipcode, :phone, :user_id, :ssn, :name)
    end
  def physician_only

    unless current_user.physician? || current_user.admin?
      redirect_to(:root,alert: "Access denied")
    end
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @states = State.all
    respond_with(@states)
  end

  def show
    respond_with(@state)
  end

  def new
    @state = State.new
    respond_with(@state)
  end

  def edit
  end

  def create
    @state = State.new(state_params)
    flash[:notice] = 'State was successfully created.' if @state.save
    respond_with(@state)
  end

  def update
    flash[:notice] = 'State was successfully updated.' if @state.update(state_params)
    respond_with(@state)
  end

  def destroy
    @state.destroy
    respond_with(@state)
  end

  private
    def set_state
      @state = State.find(params[:id])
    end

    def state_params
      params.require(:state).permit(:state)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<% if current_user.admin? %>
    <div class="row">
      <div class="panel panel-primary filterable">
        <div class="panel-heading">
          <h3 class="panel-title">Listing employees</h3>
          <div class="pull-right">
            <button class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-filter"></span> Filter</button>
          </div>
        </div>
        <table class="table">
          <thead>
          <tr class="filters">
            <th><input type="text-center" class="form-control" placeholder="Employee Name" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="Address" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="City" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="State" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="zipcode" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="phone" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="SSN" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="user id" disabled></th>
            <th colspan="3"></th>
          </tr>
          </thead>
          <% @employees.each do |employee| %>

              <tbody>

                  <tr>
                    <td><%= employee.address %></td>
                    <td><%= employee.city %></td>
                    <td><%= employee.state.state %></td>
                    <td><%= employee.zipcode %></td>
                    <td><%=  number_to_phone(employee.phone, area_code: true)   %></td>
                    <td><%= employee.ssn %></td>
                    <td><%= employee.user_id %></td>
                    <td><%= link_to 'Show', employee %></td>
                    <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
                    <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>

              </tbody>
          <% end %>
        </table>
      </div>
    </div>
<% end %>
<% if current_user.employee?%>
    <div class="row">
      <div class="panel panel-primary filterable">
        <div class="panel-heading">
          <h3 class="panel-title">Listing employees</h3>
          <div class="pull-right">
            <button class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-filter"></span> Filter</button>
          </div>
        </div>
        <table class="table">
          <thead>
          <tr class="filters">
            <th><input type="text-center" class="form-control" placeholder="Employee Name" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="Address" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="City" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="State" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="zipcode" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="phone" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="SSN" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="user id" disabled></th>
            <th colspan="3"></th>
          </tr>
          </thead>
          <% @employees.where(user_id: current_user.id).each do |employee| %>

              <tbody>

              <tr>
                <td><%= employee.address %></td>
                <td><%= employee.city %></td>
                <td><%= employee.state.state %></td>
                <td><%= employee.zipcode %></td>
                <td><%=  number_to_phone(employee.phone, area_code: true)   %></td>
                <td><%= employee.ssn %></td>
                <td><%= employee.user_id %></td>
                <td><%= link_to 'Show', employee %></td>
                <td><%= link_to 'Edit', edit_employee_path(employee) %></td>

              </tr>

              </tbody>
          <% end %>
        </table>
      </div>
    </div>
<% end %>
<script type="text/javascript">
    $(document).ready(function(){
        $('.filterable .btn-filter').click(function(){
            var $panel = $(this).parents('.filterable'),
                    $filters = $panel.find('.filters input'),
                    $tbody = $panel.find('.table tbody');
            if ($filters.prop('disabled') == true) {
                $filters.prop('disabled', false);
                $filters.first().focus();
            } else {
                $filters.val('').prop('disabled', true);
                $tbody.find('.no-result').remove();
                $tbody.find('tr').show();
            }
        });

        $('.filterable .filters input').keyup(function(e){
            /* Ignore tab key */
            var code = e.keyCode || e.which;
            if (code == '9') return;
            /* Useful DOM data and selectors */
            var $input = $(this),
                    inputContent = $input.val().toLowerCase(),
                    $panel = $input.parents('.filterable'),
                    column = $panel.find('.filters th').index($input.parents('th')),
                    $table = $panel.find('.table'),
                    $rows = $table.find('tbody tr');
            /* Dirtiest filter function ever ;) */
            var $filteredRows = $rows.filter(function(){
                var value = $(this).find('td').eq(column).text().toLowerCase();
                return value.indexOf(inputContent) === -1;
            });
            /* Clean previous no-result if exist */
            $table.find('tbody .no-result').remove();
            /* Show all rows, hide filtered ones (never do that outside of a demo ! xD) */
            $rows.show();
            $filteredRows.hide();
            /* Prepend no-result row if all rows are filtered */
            if ($filteredRows.length === $rows.length) {
                $table.find('tbody').prepend($('<tr class="no-result text-center"><td colspan="'+ $table.find('.filters th').length +'">No result found</td></tr>'));
            }
        });
    });


</script>
<% if current_user.admin? || current_user.employee? %>
    <%= link_to 'New Employee', new_employee_path ,class:"btn btn-primary" ,role:"button" %>
<% end %>
<%= paginate @employees %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>name:</strong>
  <%= @employee.name %>
</p>
<p>
  <strong>Address:</strong>
  <%= @employee.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @employee.city %>
</p>

<p>
  <strong>State:</strong>

  <%=State.where(id: @employee.state_id).pluck(:state).first%>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @employee.zipcode %>
</p>

<p>
  <strong>Phone:</strong>
  <%=  number_to_phone(@employee.phone, area_code: true)   %>
</p>

<p>
  <strong>User:</strong>
  <%= @employee.user_id %>
</p>

<p>
  <strong>Ssn:</strong>
  <%= @employee.ssn %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/insurances/edit.html.erb
<h1>Editing insurance</h1>

<%= render 'form' %>

<%= link_to 'Show', @insurance %> |
<%= link_to 'Back', insurances_path %>

app/views/insurances/index.html.erb
<% if current_user.admin? || current_user.employee?%>
    <div class="row">
      <div class="panel panel-primary filterable">
        <div class="panel-heading">
          <h3 class="panel-title">Listing insurances</h3>
          <div class="pull-right">
            <button class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-filter"></span> Filter</button>
          </div>
        </div>
        <table class="table">
          <thead>
          <tr class="filters">
            <th><input type="text-center" class="form-control" placeholder="Name" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="Coverage" disabled></th>
            <th colspan="3"></th>
          </tr>
          </thead>
          <% @insurances.each do |insurance| %>
              <tbody>
              <tr>
                <td><%= insurance.name %></td>
                <td><%= insurance.coverage %></td>
                <td> <%= link_to 'Show', insurance,class:"btn btn-primary" ,role:"button" %></td>
                <td><%= link_to 'Edit', edit_insurance_path(insurance),class:"btn btn-primary" ,role:"button"  %></td>
                <td><%= link_to 'Destroy', insurance, method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-primary" ,role:"button" %></td>
              </tr>
              </tbody>
          <% end %>
        </table>
      </div>
    </div>
<% end %>

<script type="text/javascript">
    $(document).ready(function(){
        $('.filterable .btn-filter').click(function(){
            var $panel = $(this).parents('.filterable'),
                    $filters = $panel.find('.filters input'),
                    $tbody = $panel.find('.table tbody');
            if ($filters.prop('disabled') == true) {
                $filters.prop('disabled', false);
                $filters.first().focus();
            } else {
                $filters.val('').prop('disabled', true);
                $tbody.find('.no-result').remove();
                $tbody.find('tr').show();
            }
        });

        $('.filterable .filters input').keyup(function(e){
            /* Ignore tab key */
            var code = e.keyCode || e.which;
            if (code == '9') return;
            /* Useful DOM data and selectors */
            var $input = $(this),
                    inputContent = $input.val().toLowerCase(),
                    $panel = $input.parents('.filterable'),
                    column = $panel.find('.filters th').index($input.parents('th')),
                    $table = $panel.find('.table'),
                    $rows = $table.find('tbody tr');
            /* Dirtiest filter function ever ;) */
            var $filteredRows = $rows.filter(function(){
                var value = $(this).find('td').eq(column).text().toLowerCase();
                return value.indexOf(inputContent) === -1;
            });
            /* Clean previous no-result if exist */
            $table.find('tbody .no-result').remove();
            /* Show all rows, hide filtered ones (never do that outside of a demo ! xD) */
            $rows.show();
            $filteredRows.hide();
            /* Prepend no-result row if all rows are filtered */
            if ($filteredRows.length === $rows.length) {
                $table.find('tbody').prepend($('<tr class="no-result text-center"><td colspan="'+ $table.find('.filters th').length +'">No result found</td></tr>'));
            }
        });
    });


</script>
<%= link_to 'New Insurance', new_insurance_path ,class:"btn btn-primary" ,role:"button"%>


<%= paginate @insurances %>

app/views/insurances/new.html.erb
<h1>New insurance</h1>

<%= render 'form' %>

<%= link_to 'Back', insurances_path %>

app/views/insurances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @insurance.name %>
</p>

<p>
  <strong>Coverage:</strong>
  <%= @insurance.coverage %>
</p>

<%= link_to 'Edit', edit_insurance_path(@insurance) %> |
<%= link_to 'Back', insurances_path %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<% if current_user.admin? || current_user.employee?%>
    <div class="row">
      <div class="panel panel-primary filterable">
        <div class="panel-heading">
          <h3 class="panel-title">Patients</h3>
          <div class="pull-right">
            <button class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-filter"></span> Filter</button>
          </div>
        </div>
        <table class="table">
          <thead>
          <tr class="filters">
            <th><input type="text-center" class="form-control" placeholder="Patient Name" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="Adress" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="City" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="State" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="zipcode" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="phone" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="insurance" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="user id" disabled></th>
            <th colspan="3"></th>
          </tr>
          </thead>
          <% @patients.each do |patient| %>
              <tbody>
              <tr>
                <td><%= patient.name %></td>
                <td><%= patient.adress %></td>
                <td><%= patient.city %></td>
                <td><%= State.where(id:  patient.state_id).pluck(:state).first %></td>
                <td><%= patient.zipcode %></td>
                <td><%= number_to_phone(patient.phone, area_code: true)   %></td>
                <td><%= Insurance.where(id:  patient.insurance_id).pluck(:name).first %></td>
                <td><%= patient.user_id %></td>
                <td><%= link_to 'Show', patient %></td>
                <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
                <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
              </tbody>
          <% end %>
        </table>
      </div>
    </div>
<% end %>
<% if current_user.patient?%>
    <div class="row">
      <div class="panel panel-primary filterable">
        <div class="panel-heading">
          <h3 class="panel-title">Patients</h3>
          <div class="pull-right">
            <button class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-filter"></span> Filter</button>
          </div>
        </div>
        <table class="table">
          <thead>
          <tr class="filters">
            <th><input type="text-center" class="form-control" placeholder="Patient Name" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="Adress" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="City" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="State" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="zipcode" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="phone" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="insurance" disabled></th>
            <th><input type="text-center" class="form-control" placeholder="user id" disabled></th>
            <th colspan="3"></th>
          </tr>
          </thead>
          <% @patients.where(user_id: current_user.id).each do |patient| %>
              <tbody>
              <tr>
                <td><%= patient.name %></td>
                <td><%= patient.adress %></td>
                <td><%= patient.city %></td>
                <td><%= State.where(id:  patient.state_id).pluck(:state).first %></td>
                <td><%= patient.zipcode %></td>
                <td><%= number_to_phone(patient.phone, area_code: true)   %></td>
                <td><%= Insurance.where(id:  patient.insurance_id).pluck(:name).first %></td>
                <td><%= patient.user_id %></td>
                <td><%= link_to 'Show', patient %></td>
                <td><%= link_to 'Edit', edit_patient_path(patient) %></td>

              </tr>
              </tbody>
          <% end %>
        </table>
      </div>
    </div>
<% end %>

<script type="text/javascript">
    $(document).ready(function(){
        $('.filterable .btn-filter').click(function(){
            var $panel = $(this).parents('.filterable'),
                    $filters = $panel.find('.filters input'),
                    $tbody = $panel.find('.table tbody');
            if ($filters.prop('disabled') == true) {
                $filters.prop('disabled', false);
                $filters.first().focus();
            } else {
                $filters.val('').prop('disabled', true);
                $tbody.find('.no-result').remove();
                $tbody.find('tr').show();
            }
        });

        $('.filterable .filters input').keyup(function(e){
            /* Ignore tab key */
            var code = e.keyCode || e.which;
            if (code == '9') return;
            /* Useful DOM data and selectors */
            var $input = $(this),
                    inputContent = $input.val().toLowerCase(),
                    $panel = $input.parents('.filterable'),
                    column = $panel.find('.filters th').index($input.parents('th')),
                    $table = $panel.find('.table'),
                    $rows = $table.find('tbody tr');
            /* Dirtiest filter function ever ;) */
            var $filteredRows = $rows.filter(function(){
                var value = $(this).find('td').eq(column).text().toLowerCase();
                return value.indexOf(inputContent) === -1;
            });
            /* Clean previous no-result if exist */
            $table.find('tbody .no-result').remove();
            /* Show all rows, hide filtered ones (never do that outside of a demo ! xD) */
            $rows.show();
            $filteredRows.hide();
            /* Prepend no-result row if all rows are filtered */
            if ($filteredRows.length === $rows.length) {
                $table.find('tbody').prepend($('<tr class="no-result text-center"><td colspan="'+ $table.find('.filters th').length +'">No result found</td></tr>'));
            }
        });
    });


</script>
<% if current_user.admin? || current_user.employee? %>
    <%= link_to 'New Patient', new_patient_path ,class:"btn btn-primary" ,role:"button" %>
<% end %>
<%= paginate @patients %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>name:</strong>
  <%= @patient.name %>
</p>
<p>
  <strong>Adress:</strong>
  <%= @patient.adress %>
</p>

<p>
  <strong>City:</strong>
  <%= @patient.city %>
</p>

<p>
  <strong>State:</strong>
  <%=State.where(id: @patient.state_id).pluck(:state).first%>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @patient.zipcode %>
</p>

<p>
  <strong>Phone:</strong>
  <%=  number_to_phone(@patient.phone, area_code: true)  %>
</p>

<p>
  <strong>Insurance:</strong>

  <%=Insurance.where(id: @patient.insurance_id).pluck(:name).first%>
</p>

<p>
  <strong>User:</strong>
  <%= @patient.user_id %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>

app/views/physicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>name:</strong>
  <%= @physician.name %>
</p>
<p>
  <strong>Address:</strong>
  <%= @physician.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @physician.city %>
</p>

<p>
  <strong>State:</strong>
  <%=State.where(id: @physician.state_id).pluck(:state).first%>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @physician.zipcode %>
</p>

<p>
  <strong>Phone:</strong>
  <%=  number_to_phone(@physician.phone, area_code: true)   %>
</p>

<p>
  <strong>User:</strong>
  <%= @physician.user_id %>
</p>

<p>
  <strong>Ssn:</strong>
  <%= @physician.ssn %>
</p>

<%= link_to 'Edit', edit_physician_path(@physician) %> |
<%= link_to 'Back', physicians_path %>

app/views/states/index.html.erb
<h1>Listing states</h1>

<table>
  <thead>
    <tr>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.state %></td>
        <td><%= link_to 'Show', state %></td>
        <td><%= link_to 'Edit', edit_state_path(state) %></td>
        <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New State', new_state_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>State:</strong>
  <%= @state.state %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>