config/routes.rb
Rails.application.routes.draw do
  resources :appointments

  resources :employees

  resources :physicians

  resources :patients

  resources :diagnostics

  resources :insurances

  resources :states


  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  before_save { |appointment| appointment.datetime = appointment.datetime.utc }

  belongs_to :diagnostic
  belongs_to :physician
  belongs_to :patient


  validates_uniqueness_of :datetime, scope: [:physician_id]
  validates_uniqueness_of :datetime, scope: [:patient_id]
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @appointments = Appointment.all.order(:done).page params[:page]

    respond_with(@appointments)
  end

  def show
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "appointment"
      end
    end

  end

  def new
    @selecteddate = params[:currdate]
    @appointment = Appointment.new
    respond_with(@appointment)
  end

  def edit
  end

  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.save
    respond_with(@appointment)
  end

  def update
    @selecteddate = params[:currdate]
    @appointment.update(appointment_params)
    respond_with(@appointment)
  end

  def destroy

    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      end
    respond_with(@appointment)
  end

  private
    def set_appointment
      @selecteddate = params[:currdate]
      @appointment = Appointment.find(params[:id])
    end
  def patientAndPhysician_only
    unless current_user.patient? || current_user.physician? || current_user.employee? || current_user.admin?
      redirect_to(:root,alert: "Access denied")
    end

  end
    def appointment_params
      params.require(:appointment).permit(:reason, :patient_id, :physician_id, :date, :hour, :datetime, :comment, :diagnostic_id, :done)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= simple_form_for(@appointment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <% if current_user.patient? %>
    <%= f.input :reason %>



    <div class="field">
      <%= f.label :physician_id %><br>
      <%= f.collection_select :physician_id, Physician.all, :id, :name %>
    </div>
        <% currentpatient =Patient.where(user_id: current_user.id).pluck(:id).first %>
        <%= current_user.name.to_s %>
    <%= f.hidden_field :patient_id, :value => currentpatient %>


<div  readonly='true'>

  <%= f.text_field :datetime,class:"datetimepick" %>

</div>
    <% end %>


    <% if current_user.physician? %>
        <div class="field">
          <%= f.label :diagnostic %><br>
          <%= f.collection_select :diagnostic_id, Diagnostic.all, :id, :code %>
        </div>
    <div class="field">
    <%= f.input :comment %>
    <%= f.input :done %>
      </div>
        <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<script type="text/javascript">

    var daysToDisable = [0, 6];
    $('.datepicker').datepicker({dateFormat: 'yy-mm-dd',
        beforeShowDay: disableSpecificWeekDays,
        numberOfMonths: 3,
        showButtonPanel: true,
        minute_step: 30
    })


    function disableSpecificWeekDays(date) {
        var day = date.getDay();
        for (i = 0; i < daysToDisable.length; i++) {
            if ($.inArray(day, daysToDisable) != -1) {
                return [false];
            }
        }
        return [true];
    }

    function showEventDates(date) {
        date = date - new Date(date).getTimezoneOffset() * 60000; // convert local to UTC
        // for ...
    }


    $('.datetimepick').datetimepicker({
        beforeShowDay: disableSpecificWeekDays,
        format:"Y-m-d H:i",
        formatTime: 'g:i A',
        step: 30,
        minTime: '8:00 AM',
        maxTime: '5:00 PM',
        theme:'dark',
        showTimezone: true,
        timezone: '-0600'
    });


</script>
<%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>
<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>
<link rel="stylesheet" type="text/css" href="/assets/jquery.datetimepicker.css"/>
<script type="text/javascript" src="/assets/jquery.js"></script>
<script type="text/javascript" src="/assets/jquery.datetimepicker.js"></script>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>
<%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>
<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>

app/views/appointments/index.html.erb
<h1>Listing appointments</h1>
<%= paginate @appointments %>
<% if current_user.patient? || current_user.physician?%>
<div class="row">

<br/>

  <br/>
  <% if current_user.patient? %>
    <% @appointments.where(patient_id: Patient.where(user_id: current_user.id).pluck(:id).first ).each do |appointment| %>


          <div class="col-xs-12 col-md-3">
            <div class="panel panel-primary">
              <% if  appointment.done =="done" %>
              <div class="cnrflash">
                <div class="cnrflash-inner">

                        <span class="cnrflash-label">Completed Appointment</span>
                </div>
              </div>
                  <% end %>
              <div class="panel-heading">
                <h3 class="panel-title">Patient Name: <br/><%= appointment.patient.name %></h3>
              </div>
              <div class="panel-body">
                <div class="the-price">
                  <h1>Reason:<br/>
                    <%= appointment.reason %><span class="subscript"></span></h1>

                </div>
                <table class="table">
                  <tr><td>  Fee: <%= number_to_currency(Diagnostic.where(id: appointment.diagnostic_id).pluck(:fee).first) %> </td></tr>
                  <tr><td> Physician: <%= appointment.physician.name %> </td></tr>
                  <tr class="active"><td>Date: <%= appointment.datetime.in_time_zone("Central Time (US & Canada)") %></td></tr>
                  <tr><td>Description: <%= Diagnostic.where(id: appointment.diagnostic_id).pluck(:description).first%></td></tr>
                  <tr><td>Physician Comments: </td><td></td><%= appointment.comment %></td></tr>
                </table>
              </div>
              <div class="panel-footer">
                <% unless Diagnostic.where(id: appointment.diagnostic_id).pluck(:fee).first.nil? %>
                <td> <%= link_to 'Show', appointment,class:"btn btn-primary" ,role:"button" %></td>
<% end %>
                <br/>
                <td><%= link_to 'Edit', edit_appointment_path(appointment),class:"btn btn-primary" ,role:"button"%></td>
<br/>
                    <% if (appointment.datetime > (DateTime.current + 8.hours)) %>
                        <td> <%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-primary" ,role:"button" %></a></td>

                <% end %>
                </tr>

                </div>
            </div>
          </div>

  <%end%>
  <%end%>


      <% if current_user.physician?  %>

               <% @appointments.where(physician_id: Physician.where(user_id: current_user.id).pluck(:id).first ).each do |appointment| %>




            <div class="col-xs-12 col-md-3">
              <div class="panel panel-primary">
                <% if  appointment.done =="done" %>
                    <div class="cnrflash">
                      <div class="cnrflash-inner">

                        <span class="cnrflash-label">Completed Appointment</span>
                      </div>
                    </div>
                <% end %>
                <div class="panel-heading">
                  <h3 class="panel-title">Patient Name: <br/>
                    <%= appointment.patient.name %></h3>
                </div>
                <div class="panel-body">
                  <div class="the-price">
                    <h1>Reason: <br/>
                      <%= appointment.reason %><span class="subscript"></span></h1>
                  </div>
                  <table class="table">
                    <tr><td>  Fee: <%= number_to_currency(Diagnostic.where(id: appointment.diagnostic_id).pluck(:fee).first) %> </td></tr>
                    <tr><td> Physician: <%= appointment.physician.name %> </td></tr>
                    <tr class="active"><td>Date: <%= appointment.datetime.in_time_zone("Central Time (US & Canada)") %></td></tr>
                    <tr><td>Description: <br/><%= Diagnostic.where(id: appointment.diagnostic_id).pluck(:description).first%></td></tr>
                    <tr><td>Physician Comments: <%= appointment.comment %></td></tr>
                  </table>
                </div>
                <div class="panel-footer">
                  <% unless Diagnostic.where(id: appointment.diagnostic_id).pluck(:fee).first.nil? %>
                  <td> <%= link_to 'Show', appointment,class:"btn btn-primary" ,role:"button" %></td>
<% end %>
                  <br/><% if current_user.physician? %>
                   <td><%= link_to 'Edit', edit_appointment_path(appointment),class:"btn btn-primary" ,role:"button"%></td>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>

        <%end%>




</div>
  </div>
<br>

<% end %>
<script type="text/javascript">
    $(document).ready(function(){
        $('.filterable .btn-filter').click(function(){
            var $panel = $(this).parents('.filterable'),
                    $filters = $panel.find('.filters input'),
                    $tbody = $panel.find('.table tbody');
            if ($filters.prop('disabled') == true) {
                $filters.prop('disabled', false);
                $filters.first().focus();
            } else {
                $filters.val('').prop('disabled', true);
                $tbody.find('.no-result').remove();
                $tbody.find('tr').show();
            }
        });

        $('.filterable .filters input').keyup(function(e){
            /* Ignore tab key */
            var code = e.keyCode || e.which;
            if (code == '9') return;
            /* Useful DOM data and selectors */
            var $input = $(this),
                    inputContent = $input.val().toLowerCase(),
                    $panel = $input.parents('.filterable'),
                    column = $panel.find('.filters th').index($input.parents('th')),
                    $table = $panel.find('.table'),
                    $rows = $table.find('tbody tr');
            /* Dirtiest filter function ever ;) */
            var $filteredRows = $rows.filter(function(){
                var value = $(this).find('td').eq(column).text().toLowerCase();
                return value.indexOf(inputContent) === -1;
            });
            /* Clean previous no-result if exist */
            $table.find('tbody .no-result').remove();
            /* Show all rows, hide filtered ones (never do that outside of a demo ! xD) */
            $rows.show();
            $filteredRows.hide();
            /* Prepend no-result row if all rows are filtered */
            if ($filteredRows.length === $rows.length) {
                $table.find('tbody').prepend($('<tr class="no-result text-center"><td colspan="'+ $table.find('.filters th').length +'">No result found</td></tr>'));
            }
        });
    });


</script>

<% if current_user.admin? || current_user.employee?%>
    <div class="row">
      <div class="panel panel-primary filterable">
        <div class="panel-heading">
          <h3 class="panel-title">Users</h3>
          <div class="pull-right">
            <button class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-filter"></span> Filter</button>
          </div>
        </div>
        <table class="table">
        <thead>
        <tr class="filters">
          <th><input type="text-center" class="form-control" placeholder="Physician" disabled></th>
          <th><input type="text-center" class="form-control" placeholder="Appointment ID" disabled></th>
          <th><input type="text-center" class="form-control" placeholder="Appointment Date" disabled></th>
          <th><input type="text-center" class="form-control" placeholder="Patient" disabled></th>
          <th><input type="text-center" class="form-control" placeholder="Diagnostic_code" disabled></th>
          <th><input type="text-center" class="form-control" placeholder="Diagnostic" disabled></th>
          <th><input type="text-center" class="form-control" placeholder="Fee" disabled></th>
          <th><input type="text-center" class="form-control" placeholder="Consult fee" disabled></th>
          <th><input type="text-center" class="form-control" placeholder="Total fee" disabled></th>
          <th><input type="text-center" class="form-control" placeholder="Status" disabled></th>
        </tr>
        </thead>
        <% @appointments.where(done: "done").order(:physician_id).each do |appointment| %>


              <tbody>
              <tr>
                <td><%= appointment.physician.name %></td>
                <td><%= appointment.id %></td>
                <td><%= appointment.datetime %></td>
                <td><%= appointment.patient.name %></td>
                <td><%= Diagnostic.where(id: appointment.diagnostic_id).pluck(:code).first%></td>
                <td><%= Diagnostic.where(id: appointment.diagnostic_id).pluck(:description).first %></td>
                <td><%= number_to_currency(Diagnostic.where(id: appointment.diagnostic_id).pluck(:fee).first) %></td>
                <% consultFee=50.00%>
                <td><%= number_to_currency(consultFee)%></td>
                <td><%= number_to_currency(consultFee+Diagnostic.where(id: appointment.diagnostic_id).pluck(:fee).first)%></td>
                <td><%= appointment.done %></td>
                 <td> <%= link_to 'Show', appointment,class:"btn btn-primary" ,role:"button" %></td>
              </tr>
              </tbody>
          <% end %>
            </table>
      </div>
    </div>
<% end %>

<% if current_user.patient? %>
<%= link_to  'New Appointment', new_appointment_path ,class:"btn btn-primary" ,role:"button"%>
    <% end %>
<%= paginate @appointments %>

app/views/appointments/new.html.erb
<h1>New appointment</h1>
<body>
<%= render 'form' %>
</body>
<%= link_to 'Back', appointments_path %>
<%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>
<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="invoice-title">
        <%= link_to 'Print',{:controller=>'appointments',:action=>'show' },{:class=>'button  tooltip',:target=>'_blank'} %>
        <h2>Invoice </h2><h3 class="pull-right">Invoice # <%= @appointment.id %></h3>
      </div>
      <hr>
      <div class="row">
        <div class="col-xs-6">
          <address>
            <strong>Billed To:</strong><br>
            <%= @appointment.patient.name%><br>
            <%= @appointment.patient.adress %><br>
            <%=State.where(id: @appointment.patient.state_id).pluck(:state).first%>
          </address>
        </div>
        <div class="col-xs-6 text-right">
          <address>
            <strong>Shipped To:</strong><br>
            <%= @appointment.patient.name%><br>
            <%= @appointment.patient.adress %><br>
            <%=State.where(id: @appointment.patient.state_id).pluck(:state).first%>
          </address>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-6">
          <address>
            <strong>Patient Details:</strong><br>
            <%=User.where(id: @appointment.patient.user_id).pluck(:email).first%>
            <br/>
            <strong>Physician Details:</strong><br>
            <%=  @appointment.physician.name %><br>
            <%=User.where(id: @appointment.physician.user_id).pluck(:email).first%>
          </address>
        </div>
        <div class="col-xs-6 text-right">
          <address>
            <strong>Appointment Date:</strong><br>
            <%=@appointment.datetime%><br><br>
          </address>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><strong>Appointment summary</strong></h3>
        </div>
        <div class="panel-body">
          <div class="table-responsive">
            <table class="table table-condensed">
              <thead>
              <tr>

                <td><strong>Diagnostic Code</strong></td>
                <td class="text-center"><strong> Diagnostic Description</strong></td>
                <td class="text-center"><strong> Physician Comments</strong></td>
                <td class="text-right"><strong>Diagnostic Fee</strong></td>

              </tr>
              </thead>
              <tbody>
              <!-- foreach ($order->lineItems as $line) or some such thing here -->
              <tr>
                <td><%=@appointment.diagnostic_id%></td>
                <td class="text-center"><%= Diagnostic.where(id: @appointment.diagnostic_id).pluck(:description).first%></td>
                <td class="text-center"><%= @appointment.comment %></td>
                <td class="text-right"><%= number_to_currency(Diagnostic.where(id: @appointment.diagnostic_id).pluck(:fee).first)%></td>

              </tr>
              <% consultFee=0.00%>
              <% consulttotal=consultFee %>
<% unless Diagnostic.where(id: @appointment.diagnostic_id).pluck(:fee).first.nil? %>
              <% consultFee=50.00%>
                  <% consulttotal=consultFee+Diagnostic.where(id: @appointment.diagnostic_id).pluck(:fee).first %>
                  <% end %>
              <tr>

                <td class="thick-line"></td>
                <td class="thick-line"></td>
                <td class="thick-line text-center"><strong>Subtotal</strong></td>
                <td class="thick-line text-right"><%= number_to_currency(Diagnostic.where(id: @appointment.diagnostic_id).pluck(:fee).first)%></td>
              </tr>
              <tr>

                <td class="no-line"></td>
                <td class="no-line"></td>
                <td class="no-line text-center"><strong>Consult Fee</strong></td>
                <td class="no-line text-right"><%=number_to_currency(consultFee)%></td>
              </tr>
              <tr>

                <td class="no-line"></td>
                <td class="no-line"></td>
                <td class="no-line text-center"><strong>Total</strong></td>
                <td class="no-line text-right"><%= number_to_currency(consulttotal)%></td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



<script>
    function number_pages() {
        var vars={};
        var x=document.location.search.substring(1).split('&');
        for(var i in x) {var z=x[i].split('=',2);vars[z[0]] = unescape(z[1]);}
        var x=['frompage','topage','page','webpage','section','subsection','subsubsection'];
        for(var i in x) {
            var y = document.getElementsByClassName(x[i]);
            for(var j=0; j<y.length; ++j) y[j].textContent = vars[x[i]];
        }
    }
</script>
<% if current_user.admin? %>
<%= link_to 'Edit', edit_appointment_path(@appointment) %> | <% end %>
<%= link_to 'Back', appointments_path %>
<link rel="stylesheet" type="text/css" media="print" href="print.css">