config/routes.rb
Rails.application.routes.draw do
  resources :appointments

  resources :employees

  resources :physicians

  resources :patients

  resources :diagnostics

  resources :insurances

  resources :states


  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  before_save { |appointment| appointment.datetime = appointment.datetime.utc }

  belongs_to :diagnostic
  belongs_to :physician
  belongs_to :patient


  validates_uniqueness_of :datetime, scope: [:physician_id]
  validates_uniqueness_of :datetime, scope: [:patient_id]
end

app/models/diagnostic.rb
class Diagnostic < ActiveRecord::Base


end

app/models/employee.rb
class Employee < ActiveRecord::Base
  validate :bar_exists
  has_one :user , :class_name => "User"
  belongs_to :state


  def bar_exists
    if Employee.where(user_id: self.user_id).exists? then

      errors.add(:user_id, alert:"email is already assigned to a Employee")
    end

  end
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
  has_many :patient

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  validate :bar_exists, :on => [ :create]
  has_one :user , :class_name => "User"
  has_many :physician, :through =>  :appointments
  has_many :appointment
  belongs_to :state
  belongs_to :insurance


  def bar_exists
    if Patient.where(user_id: self.user_id).exists? then

      errors.add(:user_id, alert: "email is already assigned to a patient")
    end

  end

end

app/models/physician.rb
class Physician < ActiveRecord::Base
  validate :bar_exists, :on => [ :create]
  has_one :user , :class_name => "User"
  has_many :appointment
  has_many :patient, :through =>  :appointments
  belongs_to :state

  def bar_exists
    if Physician.where(user_id: self.user_id).exists? then

      errors.add(:user_id, alert: "email is already assigned to a Physician")
    end
  end
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :employee
  has_many :patient
  has_many :physician
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:patient, :physician, :admin, :employee]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :patient
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  before_filter :patient_only
  respond_to :html

  def index
    @patients = Patient.all.page params[:page]
    respond_with(@patients)
  end

  def show
    respond_with(@patient)
  end

  def new
    @patient = Patient.new
    respond_with(@patient)
  end

  def edit
  end

  def create
    @patient = Patient.new(patient_params)
    @patient.save
    respond_with(@patient)
  end

  def update
    @patient.update(patient_params)
    respond_with(@patient)
  end

  def destroy
    @patient.destroy
    respond_with(@patient)
  end

  private
    def set_patient
      @patient = Patient.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(:adress, :city, :state_id, :zipcode, :phone, :insurance_id, :user_id, :name)
    end


  def patient_only
    unless current_user.patient? || current_user.admin?
      redirect_to(:root,alert: "Access denied")
    end
  end

end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @states = State.all
    respond_with(@states)
  end

  def show
    respond_with(@state)
  end

  def new
    @state = State.new
    respond_with(@state)
  end

  def edit
  end

  def create
    @state = State.new(state_params)
    flash[:notice] = 'State was successfully created.' if @state.save
    respond_with(@state)
  end

  def update
    flash[:notice] = 'State was successfully updated.' if @state.update(state_params)
    respond_with(@state)
  end

  def destroy
    @state.destroy
    respond_with(@state)
  end

  private
    def set_state
      @state = State.find(params[:id])
    end

    def state_params
      params.require(:state).permit(:state)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/diagnostics_helper.rb
module DiagnosticsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>


    <% if current_user.patient? %>
    <% if Patient.where(user_id: current_user.id).pluck(:id).first.nil? %>
       <li><%= link_to 'appointments', new_patient_path(@appointments) %></li>
        <% else %>
            <li><%= link_to 'appointments', appointments_path(@appointments) %></li>
          <% patientid=  Patient.where(user_id: current_user.id).pluck(:id).first.to_i  %>
            <li><%= link_to 'demographic info',  patients_path(@patients) %></li>
        <% end %>
    <% elsif current_user.physician? %>
        <% unless Physician.where(user_id: current_user.id).pluck(:id).first.nil? %>
            <li><%= link_to 'appointments', appointments_path(@appointments) %></li>
            <li><%= link_to 'demographic info',  physicians_path(@physicians) %></li>
        <% end %>

    <% elsif current_user.employee? %>
      <% unless Employee.where(user_id: current_user.id).pluck(:id).first.nil? %>
                <li><%= link_to 'appointments', appointments_path(@appointments) %></li>
                <li><%= link_to 'demographic info',  employees_path(@employees) %></li>
        <% end %>

    <% end %>

  <li><%= link_to 'Edit account', edit_user_registration_path ,class:'pull-right'%></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>

    <li><%= current_user.name %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'appointments', appointments_path(@appointments) %></li>
        <li><%= link_to 'patients', patients_path(@patients) %></li>
        <li><%= link_to 'physicians', physicians_path(@physicians) %></li>
        <li><%= link_to 'employees', employees_path(@employees) %></li>
    <li><%= link_to 'Admin', '/admin' %></li>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Scheduler" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Scheduler" %>">
    <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>
    <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>

      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>